services:
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy

  mysql:
    image: mysql:9.5
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: insight_quiz
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  mongo:
    image: mongo:8.2
    container_name: mongo-db
    restart: unless-stopped
    command: mongod --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql-data:
  mongodb_data: