services:
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
    depends_on:
      mongo:
        condition: service_healthy
  
  mongo:
    image: mongo:8.3
    container_name: mongo-db
    restart: unless-stopped
    command: mongod --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongodb_data: